
options(scipen = 999)
library(plyr)
library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
library(foreign)
library(stats)
library(janitor)
library(readr)
# library(importr)
library(parsedate)
library(rjson)
library(tidytext)
library(magrittr)

library(data.table)
library(stringi)
# library(tidyverse)
library(lubridate)
library(RODBC)
library(geojsonR)
